# Generated by Django 3.2 on 2025-04-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20250412_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
