# Generated by Django 3.2 on 2025-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('premium_expired_at', models.DateTimeField(blank=True, null=True)),
                ('isHidden', models.BooleanField(default=False)),
            ],
        ),
    ]
