# Generated by Django 3.2 on 2025-04-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
