# Generated by Django 3.2 on 2025-04-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
