"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import sys
sys.path.append('/home/alixblu/project/Spotify/backend')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zbb^@6$^lq^or+@*gj0&xr-w*1(yqzwuzhis3&gc8)-3824@2@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',  # Thêm app này để sử dụng blacklist
    'rest_framework.authtoken',  # Thêm app này để sử dụng token
    # 'rest_framework_simplejwt.token_blacklist',  # Quản lý refresh token (optional)
    'drf_spectacular',  # Swagger
    'djongo',
    'spotify_app',
    'user_management',
    'spotify_api',
    'music_library',
    'chatting',
    'channels',
]


# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     # Thêm middleware JWT 
#     'spotify_app.middlewares.JWTAuthMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'spotify_app.middlewares.JWTAuthMiddleware',  # Kiểm tra token JWT 
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Giữ lại để quản lý request.user
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "ws://127.0.0.1:5173",
    "ws://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'sec-websocket-protocol',
    'sec-websocket-extensions',
    'sec-websocket-key',
    'sec-websocket-version',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'spotify_database',  # Replace with your MongoDB database name
        'HOST': 'localhost',         # MongoDB server address
        'PORT': '27017',               # Default MongoDB port
        'ENFORCE_SCHEMA': False,       # Set to False if you don't want to enforce schema
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SECURE_SSL_REDIRECT = False
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"
DATABASE_URL = os.getenv("DATABASE_URL")
SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = os.getenv("REDIRECT_URI")
SCOPE = "user-read-private user-read-email"


# Authentication settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #   'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,  # limit mặc định khi không truyền trên URL
}

from datetime import timedelta

SIMPLE_JWT = {
    # Thời gian sống của access token (50 phút cho bảo mật cao)
    # refesh token ở fe call bị lỗi, nên tạm thời cho token sống lâu luôn
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=500), 
    
    # Thời gian sống của refresh token (7 ngày)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # Tự động tạo refresh token mới khi refresh
    'ROTATE_REFRESH_TOKENS': True,
    
    # Đưa refresh token cũ vào blacklist
    'BLACKLIST_AFTER_ROTATION': True,
    
    'UPDATE_LAST_LOGIN': False,

    # Thuật toán mã hóa
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    # Cấu hình header Authorization
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    # Sử dụng trường _id của MongoDB
    'USER_ID_FIELD': '_id', # Khớp với tên trường trong MongoDB
    'USER_ID_CLAIM': '_id',  # Khớp với claim trong token

    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    

}

# Cấu hình cho drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Spotify Clone API',
    'DESCRIPTION': 'API documentation for Spotify Clone backend',
    'VERSION': 'v1',
    'TERMS_OF_SERVICE': 'https://www.google.com/policies/terms/',
    'CONTACT': {
        'email': 'psu95228@email.com',
    },
    'LICENSE': {
        'name': 'OSS - Open Source Software _ group project',
    },
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Cấu hình security đúng cách
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'Bearer': []}],  
    
    # Cấu hình Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'docExpansion': 'none',
    },
    
    # Cấu hình OpenAPI components
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'apiKey',
                'name': 'Authorization',
                'in': 'header',
                'description': 'JWT Authorization header using the Bearer scheme. Example: "Bearer {token}"'
            }
        }
    },
    
    # Tối ưu hiệu suất
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PUBLIC': True,
}


# def get_token():
#     auth_string = SPOTIFY_CLIENT_ID + ":" + SPOTIFY_CLIENT_SECRET
#     auth_bytes = auth_string.encode('utf-8')
#     auth_base64 = base64.b64encode(auth_bytes).decode('utf-8')
#     url = 'https://accounts.spotify.com/api/token'  # Corrected to HTTPS
#     headers = {
#         'Authorization': 'Basic ' + auth_base64,
#         'Content-Type': 'application/x-www-form-urlencoded'
#     }
#     data = {
#         'grant_type': 'client_credentials'
#     }
#     response = requests.post(url, headers=headers, data=data)

#     print(f"Status Code: {response.status_code}")
#     print(f"Response Text: {response.text}")

#     try:
#         json_result = response.json()
#     except ValueError:
#         raise Exception(f"Failed to parse JSON. Response text: {response.text}")

#     if 'access_token' not in json_result:
#         raise Exception(f"Access token not found in response. Response: {json_result}")

#     access_token = json_result['access_token']
#     return access_token
# print(f"Access Token: {get_token()}")
# def get_auth_header(access_token):
#     return {"Authorization": "Bearer " + access_token}

# def search_for_artist(artist_name):
#     access_token = get_token()
#     headers = get_auth_header(access_token)
#     url = 'https://api.spotify.com/v1/search'
#     params = {
#         'q': artist_name,
#         'type': 'artist',
#         'limit': 1
#     }
#     response = requests.get(url, headers=headers, params=params)

#     print(f"Status Code: {response.status_code}")
#     print(f"Response Text: {response.text}")

#     try:
#         json_result = response.json()
#     except ValueError:
#         raise Exception(f"Failed to parse JSON. Response text: {response.text}")

#     if 'artists' in json_result and json_result['artists']['items']:
#         print("Artist found")
#         artist = json_result['artists']['items'][0]
#         print(artist['name'])
#         return artist
#     else:
#         print("No artist found")
#         return None
# search_for_artist("Taylor Swift")

# def get_songs_by_artist(artist_id):
#     access_token = get_token()
#     headers = get_auth_header(access_token)
#     url = f'https://api.spotify.com/v1/artists/{artist_id}/top-tracks'
#     params = {
#         'market': 'US'
#     }
#     response = requests.get(url, headers=headers, params=params)
#     json_result = response.json()
#     if json_result['tracks']:
#         tracks = json_result['tracks']
#         for track in tracks:
#             print(track['name'])
#         return json_result['tracks']
#     else:
#         print("No songs found")
#         return None

# Channels
ASGI_APPLICATION = 'backend.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

