# Generated by Django 3.1.12 on 2025-05-10 21:13

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '__first__'),
        ('spotify_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.song')),
            ],
            options={
                'db_table': 'playlist_songs',
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
            options={
                'db_table': 'favorite_songs',
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.CreateModel(
            name='ArtistPerform',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.song')),
            ],
            options={
                'db_table': 'artist_performances',
                'unique_together': {('artist', 'song')},
            },
        ),
    ]
