# Generated by Django 3.2 on 2025-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_library', '0002_auto_20250412_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(blank=True, max_length=255)),
                ('song_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
