# Generated by Django 4.1.13 on 2025-05-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spotify_app", "__first__"),
        ("music_library", "0002_auto_20250518_0834"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.AlterField(
            model_name="artistperform",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.artist"
            ),
        ),
        migrations.AlterField(
            model_name="artistperform",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.song"
            ),
        ),
        migrations.AlterField(
            model_name="favoritealbum",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.album"
            ),
        ),
        migrations.AlterField(
            model_name="favoriteplaylist",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.playlist"
            ),
        ),
        migrations.AlterField(
            model_name="favoritesong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.song"
            ),
        ),
        migrations.AlterField(
            model_name="playlistsong",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.playlist"
            ),
        ),
        migrations.AlterField(
            model_name="playlistsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_app.song"
            ),
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
