# Generated by Django 3.2 on 2025-04-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0004_auto_20250412_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistPerform',
        ),
        migrations.DeleteModel(
            name='FavoriteAlbum',
        ),
        migrations.DeleteModel(
            name='FavoritePlaylist',
        ),
        migrations.DeleteModel(
            name='FavoriteSong',
        ),
    ]
