# Generated by Django 3.2 on 2025-04-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0006_playlistsong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
