# Generated by Django 3.2 on 2025-04-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_user'),
        ('spotify_app', '0007_initial'),
        ('music_library', '0008_playlistsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.song')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
            options={
                'unique_together': {('user_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.playlist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
            options={
                'unique_together': {('user_id', 'playlist_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.album')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
            options={
                'unique_together': {('user_id', 'album_id')},
            },
        ),
        migrations.CreateModel(
            name='ArtistPerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.song')),
            ],
            options={
                'unique_together': {('artist_id', 'song_id')},
            },
        ),
    ]
