# Generated by Django 3.2 on 2025-04-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0009_artistperform_favoritealbum_favoriteplaylist_favoritesong'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistperform',
            table='artist_performances',
        ),
        migrations.AlterModelTable(
            name='favoritealbum',
            table='favorite_albums',
        ),
        migrations.AlterModelTable(
            name='favoriteplaylist',
            table='favorite_playlists',
        ),
        migrations.AlterModelTable(
            name='favoritesong',
            table='favorite_songs',
        ),
        migrations.AlterModelTable(
            name='playlistsong',
            table='playlist_songs',
        ),
    ]
