# Generated by Django 3.2 on 2025-04-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_playlist_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
