# Generated by Django 3.2 on 2025-04-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0005_album_artist_playlist_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
