# Generated by Django 3.2 on 2025-04-22 14:06

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0006_user'),
        ('spotify_app', '0006_auto_20250422_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('cover_img', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('total_tracks', models.IntegerField()),
                ('isfromDB', models.BooleanField(default=True)),
                ('isHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('profile_img', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('label', models.CharField(default='Artist', max_length=50)),
                ('isfromDB', models.BooleanField(default=True)),
                ('isHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('img', models.URLField(blank=True, null=True)),
                ('isfromDB', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cover_img', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isfromDB', models.BooleanField(default=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.artist'),
        ),
    ]
