# Generated by Django 3.2 on 2025-04-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='albums',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artists',
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='playlists',
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
