# Generated by Django 3.2 on 2025-05-18 08:33

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '__first__'),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.CASCADE, to='user_management.user'),
        ),
    ]
