# Generated by Django 3.2 on 2025-05-18 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '__first__'),
        ('chatting', '0002_alter_chatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ban_list',
            field=djongo.models.fields.ArrayReferenceField(default=list, on_delete=django.db.models.deletion.CASCADE, related_name='banned_rooms', to='user_management.user'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='user_management.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatting.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user_management.user')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
