# Generated by Django 3.2 on 2025-05-20 11:08

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '__first__'),
        ('user_management', '__first__'),
        ('chatting', '0003_auto_20250518_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='current_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='play_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='playing_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_app.song'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_app.playlist'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='ban_list',
            field=djongo.models.fields.ArrayReferenceField(default=list, on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to='user_management.user'),
        ),
    ]
