# Generated by Django 3.2 on 2025-05-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_auto_20250520_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='play_started_at',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='playing_song',
        ),
    ]
