# Generated by Django 3.2 on 2025-05-20 17:55

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '__first__'),
        ('chatting', '0005_auto_20250520_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='playlist',
            field=djongo.models.fields.ArrayReferenceField(default=list, on_delete=django.db.models.deletion.CASCADE, to='spotify_app.song'),
        ),
    ]
