# Generated by Django 3.2 on 2025-05-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '__first__'),
        ('chatting', '0006_alter_chatroom_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='current_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='play_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='playing_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_app.song'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_app.playlist'),
        ),
    ]
