# Generated by Django 3.2 on 2025-05-20 18:36

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '__first__'),
        ('spotify_app', '__first__'),
        ('chatting', '0007_auto_20250520_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='playlist',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='list_songs',
            field=djongo.models.fields.ArrayReferenceField(default=list, on_delete=django.db.models.deletion.CASCADE, related_name='room_songs', to='spotify_app.song'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=djongo.models.fields.ArrayReferenceField(default=list, on_delete=django.db.models.deletion.CASCADE, related_name='joined_rooms', to='user_management.user'),
        ),
    ]
