# Generated by Django 3.2 on 2025-05-20 18:57

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '__first__'),
        ('chatting', '0008_auto_20250520_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='list_songs',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='playlist',
            field=djongo.models.fields.ArrayReferenceField(default=list, on_delete=django.db.models.deletion.CASCADE, related_name='room_playlist', to='spotify_app.song'),
        ),
    ]
