# Generated by Django 3.2 on 2025-05-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0009_auto_20250520_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='playlist',
            new_name='song_list',
        ),
    ]
