# Generated by Django 3.2 on 2025-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0010_rename_playlist_chatroom_song_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
